In [21]:
np.arange(1,30,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [22]:
np.linspace(1,9,3)

array([1., 5., 9.])

In [23]:
np.random.random((5,5))

array([[0.74613576, 0.95589243, 0.19085146, 0.51667624, 0.09522113],
       [0.98790395, 0.07149282, 0.68598752, 0.88695134, 0.48723188],
       [0.7818648 , 0.40030844, 0.4792578 , 0.7591234 , 0.6596822 ],
       [0.21195281, 0.16237468, 0.49587726, 0.42207851, 0.49423446],
       [0.38044989, 0.08902913, 0.00475663, 0.85111695, 0.70704607]])

In [24]:
np.random.normal(1,2,(4,4))

array([[ 2.21527842, -0.27191872, -0.05511749,  1.04625586],
       [-2.58475068,  1.1023875 ,  3.4882231 ,  2.85288196],
       [-1.52228777, -0.0145421 ,  1.15927204, -1.18739487],
       [-1.71265857,  1.00744502, -0.13335262,  0.52630688]])

In [25]:
np.random.randint(3,20,(4,4))

array([[10, 15,  9,  3],
       [10,  8,  8, 14],
       [ 4,  8,  7,  7],
       [ 4,  3,  8, 12]])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

np.random.seed(0)
x1=np.random.randint(10, size=6)
x2=np.random.randint(10, size=(3,4))
x3=np.random.randint(10, size=(3,4,5))
